extends: 'eslint:recommended'
env:
  es6: true
  node: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - always
